### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by finleyexp** [TeamBitBean/bitbean-digital-cash#1]
I wanted to download the wallet generator so that I could make an offline wallet, however, there is only the readme.md file in this folder.

**Comment by teambean** [comment]
Hi! 

You can download here: http://www.bitbean.org/cash/index.html (RMB click "Save Link As") 


Best Regards, 

-- 
Shawn Kent 
Project Manager & Lead Developer 
Bean Core, Team Bean, BitBean 
"BitBean, Fast..Simple..Secure..More Than Just a Digital Currency!" 
www.bitbean.org

**Comment by finleyexp** [comment]
Rock on. Thanks!
